name: test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  math_expressions: ^2.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.0
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF" # Background color of the splash screen
  image: assets/image/splash.png # Adjusted path for consistency
  android: true
  ios: true
  fullscreen: true # Optional: makes the splash screen fullscreen

flutter:
  uses-material-design: true

  assets:
    - asset/image/login.png
    - asset/image/splash.png
    - asset/image/hisyam.png

  fonts:
    - family: Outfit
      fonts:
        - asset: asset/font/Outfit-VariableFont_wght.ttf
